import styles from './FAQSection.module.scss';

const FAQ_CATEGORIES = [
  { id: 'reparations', label: 'Réparations et délais' },
  { id: 'garanties', label: 'Garanties' },
  { id: 'avant-intervention', label: 'Avant l’intervention' },
  { id: 'prestations', label: 'Prestations et matériel' },
  { id: 'deplacement', label: 'Déplacement et zone' },
  { id: 'contact', label: 'Contact et rendez-vous' },
  { id: 'suivi', label: 'Suivi après intervention' },
  { id: 'depannage', label: 'Dépannage et urgences' },
  { id: 'tarifs', label: 'Tarifs et devis' },
  { id: 'paiement', label: 'Paiement et facturation' },
  { id: 'donnees', label: 'Données et confidentialité' },
  { id: 'reclamations', label: 'Réclamations et litiges' },
] as const;

type CategoryId = (typeof FAQ_CATEGORIES)[number]['id'];

const FAQ_ITEMS: Array<{ categoryId: CategoryId; question: string; answer: string }> = [
  { categoryId: 'reparations', question: 'Combien de temps dure une réparation type ?', answer: 'La durée d’une réparation varie selon la nature de la panne et la disponibilité des pièces (notamment en cas de commande). Un diagnostic et une estimation des délais sont communiqués au client avant toute intervention. Certaines prestations peuvent être réalisées le jour même ; d’autres sont subordonnées à la réception des pièces. Les délais indiqués restent donnés à titre indicatif. La facturation est établie au forfait ou au tarif convenu dans le devis ; aucun taux horaire n’est appliqué.' },
  { categoryId: 'reparations', question: 'Comment se déroule une réparation (étapes) ?', answer: 'Après votre demande, un diagnostic est réalisé pour identifier la cause du problème. Une proposition de solution et un devis (délais et tarif) vous sont communiqués. Aucune intervention engageante (réparation, démontage) n’est effectuée sans votre accord préalable et sans acceptation du devis. Une fois le devis accepté, la prestation est réalisée ; les délais à chaque étape vous sont indiqués à titre indicatif.' },
  { categoryId: 'reparations', question: 'Que se passe-t-il si des pièces doivent être commandées ?', answer: 'Si des pièces doivent être commandées, le délai de la prestation inclut le temps de livraison. La commande, le fournisseur et une estimation du délai peuvent être indiqués dans le devis. L’intervention est réalisée après réception des pièces. Le client peut être informé de l’avancement si nécessaire.' },
  { categoryId: 'reparations', question: 'Puis-je récupérer mon équipement le jour même ?', answer: 'Cela dépend de la nature de la prestation et de la disponibilité des pièces. Certaines interventions (diagnostic simple, petit dépannage, configuration) peuvent permettre une remise le jour même ; d’autres, notamment en cas de commande de pièces ou de récupération de données, nécessitent plusieurs jours. Une estimation vous est communiquée après le diagnostic et avant toute intervention.' },
  { categoryId: 'garanties', question: 'Les pièces sont-elles garanties ?', answer: 'Les pièces neuves installées bénéficient exclusivement des garanties légales et/ou commerciales du fabricant ou du fournisseur. Aucune garantie commerciale supplémentaire n’est accordée par ARKENYX sur les pièces. Les conditions et durées de garantie applicables vous sont précisées lors de l’établissement du devis ou de la commande.' },
  { categoryId: 'garanties', question: 'Proposez-vous une garantie sur l’intervention ?', answer: 'L’intervention ne comprend pas de garanties commerciales sur la main d’œuvre. Les pièces installées ne bénéficient que de la garantie constructeur. Toute nouvelle panne indépendante de l’intervention fera l’objet d’un nouveau diagnostic. L’obligation de moyens et la responsabilité civile professionnelle restent applicables.' },
  { categoryId: 'garanties', question: 'Comment faire jouer la garantie sur une pièce installée ?', answer: 'ARKENYX n’effectue pas d’achat-revente de pièces : c’est vous qui achetez ou fournissez les pièces. La garantie sur une pièce est donc celle du vendeur ou du fabricant auprès desquels vous vous êtes approvisionné. Pour faire jouer la garantie, reportez-vous aux conditions du vendeur et aux informations figurant sur l’emballage ou la facture d’achat. Nous pouvons vous orienter sur les démarches si besoin.' },
  { categoryId: 'garanties', question: 'Qui fournit les pièces (montage, réparation) ?', answer: 'Les pièces sont achetées ou fournies par le client. Nous pouvons vous conseiller sur le choix et la compatibilité des pièces (neuves ou d’occasion), mais nous ne les achetons pas pour vous. Si vous fournissez des pièces non conformes à nos recommandations ou incompatibles, la responsabilité n’incombe pas à ARKENYX. Les garanties éventuelles sur les pièces sont celles du vendeur auprès duquel vous vous êtes approvisionné.' },
  { categoryId: 'avant-intervention', question: 'Que devez-vous faire avant de nous confier votre PC ?', answer: 'Il est recommandé de sauvegarder vos données importantes et de conserver une trace de vos identifiants (système d’exploitation et logiciels). La sauvegarde des données relève de la responsabilité du client avant toute prise en charge. Un accompagnement pour la réalisation d’une sauvegarde peut être proposé à titre facultatif ; sa mise en œuvre ne constitue pas une obligation contractuelle d’ARKENYX.' },
  { categoryId: 'avant-intervention', question: 'Faut-il apporter les câbles et périphériques (souris, clavier) ?', answer: 'Pour un PC fixe, l’unité centrale suffit : nous disposons du matériel nécessaire pour le diagnostic. Si le problème est lié à un périphérique en particulier, nous vous l’indiquerons et pourrons vous demander de l’apporter. Pour un portable, l’appareil et son chargeur sont en général suffisants. Les modalités peuvent être précisées lors de la prise de rendez-vous ou du devis.' },
  { categoryId: 'avant-intervention', question: 'Mon équipement est-il assuré pendant la prise en charge ?', answer: 'L’équipement reste votre propriété. Nous le prenons en charge avec diligence (obligation de moyens). Nous vous recommandons de vérifier vos assurances (multirisque habitation, etc.) pour la couverture des biens confiés. Toute disposition particulière en matière de responsabilité ou d’assurance peut être précisée au devis ou au contrat.' },
  { categoryId: 'avant-intervention', question: 'Pendant combien de temps puis-je laisser mon équipement chez vous ?', answer: 'La durée de prise en charge correspond au temps nécessaire à l’intervention et à un délai raisonnable pour la récupération par le client. Elle est indiquée ou convenue lors de l’établissement du devis. Aucun stockage prolongé au-delà du nécessaire n’est prévu ; vous êtes informé lorsque l’équipement est prêt à être récupéré.' },
  { categoryId: 'prestations', question: 'Quels types de matériel prenez-vous en charge ?', answer: 'Nous intervenons principalement sur PC fixes, PC portables et périphériques informatiques. Nous n’intervenons pas sur les smartphones ni sur les tablettes. Nous n’intervenons pas sur les solutions de stockage de type NAS en tant que telles, en dehors d’éventuelles opérations de récupération de données sur les supports de stockage lorsqu’elles sont techniquement possibles.' },
  { categoryId: 'prestations', question: 'Intervenez-vous pour les particuliers et les professionnels ?', answer: 'Oui. Les prestations s’adressent aux particuliers comme aux professionnels. Elles restent toutefois à échelle humaine et adaptées à une structure d’indépendant : les projets d’envergure (par exemple infrastructure réseau complète, parc de nombreux postes, déploiements massifs) ne relèvent pas de notre périmètre et sont à confier à des structures adaptées.' },
  { categoryId: 'prestations', question: 'Proposez-vous le montage de PC sur mesure ?', answer: 'Oui. Nous proposons le conseil en configuration et compatibilité des pièces, ainsi que le montage et l’installation de base (système d’exploitation, pilotes). Les pièces sont fournies ou achetées par le client ; nous ne pratiquons pas l’achat-revente. Un devis est établi sur demande en fonction de la configuration envisagée et des prestations souhaitées.' },
  { categoryId: 'prestations', question: 'Réalisez-vous la récupération de données ?', answer: 'Oui. La récupération de données est réalisée en atelier : vous nous confiez le support concerné (disque interne ou externe, clé USB, etc.). La faisabilité et le résultat ne peuvent être garantis à l’avance, selon l’état du support et la nature de la panne. Un diagnostic et un devis vous sont communiqués avant toute intervention engageante. Les tarifs varient selon la difficulté et le volume concerné.' },
  { categoryId: 'prestations', question: 'Quelles modalités pour les professionnels ?', answer: 'Les prestations sont les mêmes pour les particuliers et les professionnels (devis, facture, moyens de paiement). La facture comporte les mentions légales obligatoires (SIRET, etc.) et peut être établie aux coordonnées de votre entreprise. Des délais de paiement ou des conventions spécifiques peuvent être envisagés au cas par cas ; les conditions sont précisées sur le devis ou par accord écrit.' },
  { categoryId: 'prestations', question: 'Que faire des pièces remplacées ou des équipements en fin de vie ?', answer: 'Les pièces remplacées et les équipements dont vous ne souhaitez plus vous défaire vous restent ; vous en restez propriétaire. ARKENYX ne reprend pas les équipements en fin de vie (déchets d’équipements électriques et électroniques – DEEE) sauf accord spécifique : leur élimination ou leur reprise relève de votre responsabilité, dans le respect de la réglementation en vigueur (reprise en magasin, déchetterie, éco-organisme agréé, etc.).' },
  { categoryId: 'deplacement', question: 'Intervention à domicile ou prise en charge du matériel ?', answer: 'Une intervention à domicile peut être prévue lorsque la prestation le justifie (PC fixe, montage sur site, configuration, etc.). Les prestations de récupération de données sont réalisées sur nos locaux : le support de stockage concerné (disque interne ou externe) est confié par le client ou récupéré sur place, puis traité en atelier. Aucune prise en charge à distance (guidage ou intervention à distance) n’est proposée. Les modalités précises (déplacement, remise du matériel) sont fixées lors de l’établissement du devis ou de la commande.' },
  { categoryId: 'deplacement', question: 'Intervenez-vous partout, dans quelle zone ?', answer: "Non. Les interventions se font en Mayenne et, dans une moindre mesure, sur le secteur est d'Ile-et-Vilaine. La zone exacte et les conditions de déplacement peuvent être précisées à la demande ou lors du devis." },
  { categoryId: 'deplacement', question: 'Le déplacement est-il facturé ?', answer: 'Oui. Le déplacement est gratuit dans un rayon de 10 km autour d’Ahouillé. Au-delà, il est facturé 0,50 € par kilomètre. Le détail et le montant sont à définir et à rappeler sur le devis.' },
  { categoryId: 'deplacement', question: 'Où puis-je déposer ou récupérer mon matériel ?', answer: 'L’adresse de nos locaux pour le dépôt et la récupération du matériel vous est communiquée lors de la prise de rendez-vous ou sur le devis. Vous pouvez y déposer votre équipement et le récupérer une fois la prestation terminée. Les modalités (horaires de dépôt, délai de récupération) sont convenues avec vous.' },
  { categoryId: 'deplacement', question: 'Comment sont calculés le rayon gratuit et les kilomètres ?', answer: 'Le rayon gratuit de 10 kilomètres est calculé depuis le siège de l’entreprise. Au-delà, il est facturé 0,50 € par kilomètre. Le détail du calcul (trajet aller, aller-retour) et le montant figurent sur le devis avant toute intervention.' },
  { categoryId: 'contact', question: 'Comment vous joindre ou prendre rendez-vous ?', answer: 'Plusieurs moyens : par e-mail (contact@arkenyx.fr), par téléphone (06 45 65 84 48), ou via le site (bouton « Demander un devis » ou formulaire en bas de page). La prise de rendez-vous et les modalités sont convenues avec vous après votre demande.' },
  { categoryId: 'contact', question: 'Sous quel délai recevrai-je une réponse ou un devis ?', answer: 'ARKENYX s’engage à répondre à toute demande dans les meilleurs délais possibles. Aucun délai contractuel n’est garanti : le délai de réponse ou d’établissement du devis varie selon l’activité et les demandes en cours, et reste à titre indicatif.' },
  { categoryId: 'contact', question: 'La prise de rendez-vous est-elle obligatoire ?', answer: 'Oui. Un rendez-vous est nécessaire pour garantir la disponibilité et organiser les interventions. Nous ne recevons pas à l’improviste : le dépôt ou la récupération du matériel, ainsi que les interventions à domicile, sont organisés sur rendez-vous. Les modalités sont convenues avec vous lors de votre demande.' },
  { categoryId: 'contact', question: 'Comment annuler ou reporter un rendez-vous ?', answer: 'En nous contactant par e-mail (contact@arkenyx.fr) ou par téléphone (06 45 65 84 48) dans les meilleurs délais. En cas d’annulation ou de report, les modalités applicables (préavis, éventuelle facturation) peuvent être précisées au devis ou à la commande ; à défaut, nous vous invitons à nous contacter le plus tôt possible pour réorganiser la prestation.' },
  { categoryId: 'suivi', question: 'Proposez-vous un suivi après l’intervention ?', answer: 'Un suivi ou un accompagnement sur la durée peut être proposé sous forme de prestations contractuelles payantes (devis dédié). Par ailleurs, en cas de dysfonctionnement signalé par le client après une intervention et susceptible d’y être lié, un examen est réalisé pour en identifier la cause. Si la cause est imputable à l’intervention réalisée par ARKENYX, la mise en conformité est prise en charge par ARKENYX. Si la cause est imputable au client, à un tiers ou à un fait extérieur, le diagnostic et toute intervention complémentaire sont facturés selon le tarif en vigueur.' },
  { categoryId: 'suivi', question: 'Que faire si un problème apparaît après l’intervention ?', answer: 'Signalez-le nous par e-mail ou téléphone dans les meilleurs délais. Nous réalisons un examen pour en identifier la cause. Si elle est imputable à l’intervention réalisée par ARKENYX, la mise en conformité est prise en charge. Si elle est imputable au client, à un tiers ou à un fait extérieur, le diagnostic et toute intervention complémentaire sont facturés selon le tarif en vigueur.' },
  { categoryId: 'suivi', question: 'Remettez-vous un document après l’intervention ?', answer: 'Une facture est remise après chaque prestation, avec le détail des prestations réalisées et les mentions légales obligatoires. Tout autre document (récapitulatif des travaux, bon de restitution) peut être prévu au devis ou à la commande selon les besoins.' },
  { categoryId: 'depannage', question: 'Que faire si mon PC ne démarre plus du tout ?', answer: 'Un PC qui ne démarre plus peut avoir plusieurs causes (alimentation, matériel, logiciel). Avant toute intervention de notre part, il est recommandé d’éviter les manipulations hasardeuses et, si possible, de noter les symptômes (message affiché, voyants, bruits anormaux). La prise en charge consiste en un diagnostic pour identifier l’origine du problème. Une proposition de solution et un devis vous sont ensuite communiqués. Aucune réparation ou intervention engageante n’est réalisée sans votre accord préalable et sans acceptation du devis.' },
  { categoryId: 'depannage', question: 'Acceptez-vous les interventions urgentes ?', answer: 'Des interventions urgentes peuvent être envisagées sous réserve de nos disponibilités, de la nature de la panne et de la localisation de l’intervention. Elles sont réalisées uniquement pendant les horaires d’ouverture habituels, sauf accord spécifique, et ne constituent en aucun cas une obligation pour ARKENYX. Toute demande est d’abord évaluée (type de problème, distance, faisabilité) ; un diagnostic et un devis précisant les délais et, le cas échéant, toute majoration liée au caractère urgent de la demande sont communiqués au client pour acceptation préalable.' },
  { categoryId: 'depannage', question: 'Que ne dois-je pas faire quand mon équipement ne fonctionne plus ?', answer: 'Il est recommandé d’éviter les manipulations hasardeuses : ne pas ouvrir l’équipement sans compétence, ne pas tenter de récupération de données soi-même sur un support endommagé (risque d’aggravation). Noter les symptômes (messages affichés, voyants, bruits anormaux) et nous contacter pour un diagnostic. Aucune intervention engageante ne sera réalisée sans votre accord et sans acceptation du devis.' },
  { categoryId: 'depannage', question: 'Intervenez-vous en dehors des horaires habituels (soir, week-end) ?', answer: 'Les interventions ont lieu pendant les horaires d’ouverture habituels. Un déplacement en soirée ou le week-end peut éventuellement être envisagé sur accord spécifique, sous réserve de nos disponibilités ; il fera l’objet d’un devis préalable et peut donner lieu à une majoration. Aucune obligation n’incombe à ARKENYX en la matière.' },
  { categoryId: 'tarifs', question: 'Comment sont calculés les tarifs ?', answer: 'Les tarifs sont affichés clairement pour chaque prestation. Un devis gratuit est établi avant toute intervention ; aucun coût caché n’est pratiqué. Certaines prestations (création de site, récupération de données, etc.) font l’objet de tarifs variables selon les circonstances — volume de données, difficulté technique, complexité du projet — détaillés et chiffrés dans le devis. Les tarifs d’ARKENYX sont alignés sur les pratiques du marché et s’inscrivent dans une démarche de proximité et de transparence ; le détail et le montant définitif sont toujours fixés dans le devis accepté par le client.' },
  { categoryId: 'tarifs', question: 'Le devis est-il gratuit et combien de temps reste-t-il valable ?', answer: 'L’établissement du devis est gratuit. La durée de validité de l’offre figure parmi les mentions portées sur chaque devis et lie ARKENYX pendant ce délai aux tarifs et conditions indiqués. À l’expiration de cette durée, l’offre devient caduque ; toute nouvelle demande fera l’objet d’un nouveau devis. Une durée de validité de 30 jours est appliquée sauf mention contraire sur le document.' },
  { categoryId: 'tarifs', question: 'Les tarifs sont-ils TTC ou HT ?', answer: 'ARKENYX est en régime micro-entreprise et relève de la franchise en base de TVA (article 293 B du CGI). Les tarifs indiqués sont donc hors taxes : la TVA n’est pas applicable et ne peut être facturée. En cas de dépassement des seuils de chiffre d’affaires prévus par la réglementation (pour les prestations de services : 37 500 € l’année précédente / 41 250 € en cours d’année), ARKENYX serait soumis à la TVA et les tarifs seraient alors communiqués en conséquence (HT ou TTC selon le cas).' },
  { categoryId: 'tarifs', question: 'Le devis engage-t-il le client ?', answer: 'Le devis constitue une offre. Le contrat entre les deux parties n’est formé et ratifié qu’à partir de l’acceptation du client, validée conformément aux lois en vigueur et au cadre juridique applicable (devis signé et retourné, ou accord explicite par e-mail ou oral confirmé, selon les CGV). Aucune prestation n’est réalisée ni facturée avant cette ratification. À l’expiration du délai de validité indiqué sur le document (30 jours par défaut), l’offre devient caduque et toute nouvelle demande fera l’objet d’un nouveau devis.' },
  { categoryId: 'tarifs', question: 'Le tarif final peut-il dépasser le montant du devis ?', answer: 'Tant que le périmètre de la prestation reste inchangé, le montant facturé correspond au devis accepté. Si des éléments nouveaux apparaissent (lors du diagnostic ou à votre demande), un avenant ou un nouveau devis vous est proposé avant toute intervention complémentaire ; vous n’êtes pas tenu de l’accepter. Le détail des prestations et montants figure sur le devis et la facture.' },
  { categoryId: 'paiement', question: 'Quels moyens de paiement acceptez-vous ?', answer: 'Les règlements sont acceptés par carte bancaire, virement et espèces. Les paiements par chèque ne sont pas acceptés. Les modalités de paiement (acompte, solde, délais) sont précisées sur le devis ou la facture.' },
  { categoryId: 'paiement', question: 'Fournissez-vous une facture ?', answer: 'Oui. Une facture est établie après chaque prestation. Elle comporte le détail des prestations réalisées, les éventuelles majorations (déplacement, etc.) et les mentions légales obligatoires, notamment la mention de franchise de TVA (TVA non applicable, article 293 B du CGI) lorsque ARKENYX n’est pas assujetti à la TVA.' },
  { categoryId: 'paiement', question: 'À quel moment le paiement est-il dû ?', answer: 'Les modalités de paiement (acompte éventuel, solde à la remise du matériel ou à la fin de la prestation) sont précisées sur le devis ou la facture. En l’absence de mention contraire, le règlement est dû à la livraison de la prestation.' },
  { categoryId: 'paiement', question: 'Un acompte est-il demandé ?', answer: 'Un acompte peut être demandé pour certaines prestations ; le montant ou les conditions sont indiqués sur le devis. Aucun acompte n’est prélevé sans accord du client préalable à la réalisation de la prestation.' },
  { categoryId: 'paiement', question: 'Pour les professionnels, proposez-vous des délais de paiement ?', answer: 'Des délais de paiement (par exemple 30 jours, 45 jours fin de mois) peuvent être envisagés pour les professionnels, sous réserve d’accord préalable et de conditions précisées sur le devis ou par écrit. En l’absence de mention, le règlement est dû à la livraison de la prestation. En cas de retard, des pénalités de retard peuvent être appliquées conformément aux articles L.441-6 et L.441-10 du Code de commerce (détail sur la facture ou dans les CGV).' },
  { categoryId: 'donnees', question: 'Que deviennent mes données pendant l’intervention ?', answer: 'L’accès aux données est strictement limité à ce qui est nécessaire à la réalisation de la prestation. Aucune copie ni conservation des données n’est effectuée sans accord préalable du client. Les données sont traitées dans le respect du secret professionnel et des obligations applicables en matière de protection des données personnelles (RGPD). Aucune utilisation ni divulgation à des tiers n’est pratiquée en dehors du cadre de l’intervention.' },
  { categoryId: 'donnees', question: 'Conservez-vous mes données après l’intervention ?', answer: 'Non. Aucune copie de vos données n’est conservée au-delà du strict nécessaire à la réalisation de la prestation. Une fois la prestation terminée et les données ou le support restitués, aucune conservation durable n’est pratiquée sans votre accord explicite. Les données de contact (pour la relation client et la facturation) sont traitées conformément à notre politique de confidentialité.' },
  { categoryId: 'donnees', question: 'Où consulter la politique de confidentialité et quels sont mes droits ?', answer: 'La politique de confidentialité est disponible sur le site (lien en bas de page ; la page Mentions légales en fait mention). Elle décrit les données collectées, les finalités du traitement, la durée de conservation et vos droits (accès, rectification, effacement, limitation, opposition, portabilité) conformément au Règlement (UE) 2016/679 (RGPD). Pour toute question ou exercice de vos droits, contactez-nous à contact@arkenyx.fr ou 06.45.65.84.48 ; vous pouvez aussi introduire une réclamation auprès de la CNIL (cnil.fr).' },
  { categoryId: 'reclamations', question: 'Comment faire une réclamation ?', answer: 'Toute réclamation doit être adressée par écrit à ARKENYX : par e-mail à contact@arkenyx.fr (recommandé) ou par courrier à l’adresse figurant sur votre facture si vous en disposez. Précisez l’objet de la réclamation, les références de la prestation concernée (devis, facture) et les éléments de fait. ARKENYX s’engage à examiner toute réclamation et à y répondre dans les meilleurs délais. Les modalités détaillées figurent dans les conditions générales de vente (CGV).' },
  { categoryId: 'reclamations', question: 'En cas de litige, à qui m’adresser ?', answer: 'En cas de litige, le client est invité à contacter ARKENYX en priorité par écrit (contact@arkenyx.fr) pour tenter une résolution amiable. Si le litige persiste, les conditions générales de vente (CGV) et le droit français sont applicables. Conformément aux articles L.612-1 et suivants du Code de la consommation, un dispositif de médiation de la consommation sera mis en place dès le début effectif de l’activité commerciale auprès des particuliers ; les coordonnées du médiateur compétent seront alors communiquées dans les CGV.' },
  { categoryId: 'reclamations', question: 'Quel délai pour répondre à une réclamation ?', answer: 'ARKENYX s’engage à traiter toute réclamation dans les meilleurs délais. Aucun délai contractuel de réponse n’est garanti : le délai varie selon la nature de la réclamation et les éléments à examiner. Une accusé de réception ou une première réponse peut vous être adressée ; un délai raisonnable est appliqué pour l’examen et la réponse détaillée.' },
];

function getItemsByCategory() {
  const map = new Map<CategoryId, typeof FAQ_ITEMS>();
  for (const item of FAQ_ITEMS) {
    const list = map.get(item.categoryId) ?? [];
    list.push(item);
    map.set(item.categoryId, list);
  }
  return map;
}

function FaqItem({ item }: { item: (typeof FAQ_ITEMS)[0] }) {
  return (
    <details className={styles.item}>
      <summary className={styles.question}>{item.question}</summary>
      <p className={styles.answer}>{item.answer}</p>
    </details>
  );
}

export default function FAQSection() {
  const itemsByCategory = getItemsByCategory();

  return (
    <section className={styles.section} id="faq" aria-labelledby="faq-title">
      <div className={styles.faqWrap}>
        <h2 id="faq-title" className={styles.heading}>Questions fréquentes</h2>
        <p className={styles.intro}>
          Quelques réponses pour vous aider. Une autre question ? N’hésitez pas à nous contacter.
        </p>
        <div className={styles.categoryList}>
          {FAQ_CATEGORIES.map((cat) => {
            const items = itemsByCategory.get(cat.id) ?? [];
            if (items.length === 0) return null;
            return (
              <details key={cat.id} className={styles.category}>
                <summary className={styles.categoryTitle}>{cat.label}</summary>
                <div className={styles.categoryContent}>
                  <div className={styles.questionsGrid}>
                    {items.map((item, i) => (
                      <FaqItem key={`${cat.id}-${i}`} item={item} />
                    ))}
                  </div>
                  <div className={styles.questionsGridTablet}>
                    {[0, 1].map((col) => (
                      <div key={col} className={styles.questionsColumn}>
                        {items.map((item, i) => (i % 2 === col ? <FaqItem key={`${cat.id}-${i}`} item={item} /> : null))}
                      </div>
                    ))}
                  </div>
                  <div className={styles.questionsGridDesktop}>
                    {[0, 1, 2].map((col) => (
                      <div key={col} className={styles.questionsColumn}>
                        {items.map((item, i) => (i % 3 === col ? <FaqItem key={`${cat.id}-${i}`} item={item} /> : null))}
                      </div>
                    ))}
                  </div>
                </div>
              </details>
            );
          })}
        </div>
      </div>
    </section>
  );
}
